### ISSUE TITLE
Path is not added correctly

### ISSUE THREAD

**Issue by HerrMotz** [getcone/Cone#8]
The program directed me to my userprofile path correctly, but it seemed to not have added `%ProgramFiles%\Hell.sh\Cone\path` to the environment variables, because it did not find the file "cone" at the end of the installation routine.

System info:
- Windows 10
- php was already installed

**Comment by timmyrs** [comment]
I think the issue here is that on Windows the installation program summons a new `cmd.exe` instance, which is considered to be a child, and thereby inherits all the environment variables of the parent, excluding the newly-added ones.
